In [1]:
import pickle
from tqdm import tqdm
import numpy as np
# import matplotlib.pyplot as plt
import networkx as nx
import sys
import random
sys.path.append(r'c:\\Users\\rotim\\OneDrive\\Documents\\Reading\\graph-code\\Skoltech-PhD-Thesis\\_codes\\SIR\\Influential-nodes-identification-in-complex-networks-via-information-entropy')
from algorithms import *


In [2]:
data_file = 'CEnew' # 'HepPh'
G = nx.read_adjlist(data_file)
G.remove_edges_from(nx.selfloop_edges(G))
nodes = list(nx.nodes(G))
for node in nodes:
    if G.degree(node) == 0:
        G.remove_node(node)

In [3]:
print(nx.number_of_nodes(G), nx.number_of_edges(G))

453 2025


In [5]:
infect_prob = compute_probability(G)*1.5
infect_prob

0.03836535182448562

In [6]:
atio = 1
cover_prob = infect_prob / atio

In [14]:
max_iter = 20000

In [15]:
max_ = 0.009
max_topk = round(max_ * nx.number_of_nodes(G))
print(max_topk)

4


In [16]:
degreerank = degree(G, max_topk)
print(degreerank)
print('done!')

[('15', ' '), ('2', ' '), ('5', ' '), ('97', ' ')]
done!


In [17]:
get_topk(degreerank, max_topk)

['15', '2', '5', '97']

In [18]:


SIR_sample_result = SIR(G, get_topk(degreerank, max_topk), infect_prob,cover_prob, max_iter)
print(SIR_sample_result)

(167, {0: 4, 1: 4, 2: 4, 3: 4, 4: 4, 5: 4, 6: 4, 7: 4, 8: 4, 9: 5, 10: 5, 11: 5, 12: 6, 13: 6, 14: 6, 15: 7, 16: 8, 17: 8, 18: 8, 19: 8, 20: 8, 21: 8, 22: 9, 23: 9, 24: 9, 25: 9, 26: 11, 27: 11, 28: 11, 29: 11, 30: 12, 31: 13, 32: 13, 33: 14, 34: 14, 35: 14, 36: 14, 37: 14, 38: 14, 39: 14, 40: 14, 41: 14, 42: 14, 43: 15, 44: 15, 45: 15, 46: 15, 47: 15, 48: 16, 49: 16, 50: 17, 51: 17, 52: 17, 53: 17, 54: 17, 55: 17, 56: 17, 57: 17, 58: 17, 59: 17, 60: 17, 61: 17, 62: 17, 63: 17, 64: 17, 65: 17, 66: 17, 67: 17, 68: 17, 69: 17, 70: 17, 71: 17, 72: 17, 73: 17, 74: 17, 75: 17, 76: 17, 77: 17, 78: 17, 79: 17, 80: 17, 81: 17, 82: 17, 83: 17, 84: 17, 85: 17, 86: 17, 87: 17, 88: 17, 89: 17, 90: 17, 91: 17, 92: 17, 93: 17, 94: 17, 95: 17, 96: 17, 97: 17, 98: 17, 99: 17, 100: 17, 101: 17, 102: 17, 103: 17, 104: 17, 105: 17, 106: 17, 107: 17, 108: 17, 109: 17, 110: 17, 111: 17, 112: 17, 113: 17, 114: 17, 115: 17, 116: 17, 117: 17, 118: 17, 119: 17, 120: 17, 121: 17, 122: 17, 123: 17, 124: 17, 125:

In [4]:
# to-get infected set
r = 0.009
top_k = round(nx.number_of_nodes(G) * r)
print(r, top_k)
rank = []

0.009 4


In [5]:
r = [0.0015, 0.003, 0.0045, 0.006, 0.0075, 0.009]
topk_list = []
for k in r:
    topk = round(nx.number_of_nodes(G) * k)
    print(k, topk)
    topk_list.append(topk)

print(topk_list)

0.0015 1
0.003 1
0.0045 2
0.006 3
0.0075 3
0.009 4
[1, 1, 2, 3, 3, 4]


In [6]:
max_ = 0.009
max_topk = round(max_ * nx.number_of_nodes(G))
print(max_topk)

degreerank = degree(G, max_topk)
print(degreerank)

4
[('15', ' '), ('2', ' '), ('5', ' '), ('97', ' ')]


In [7]:
#nbrs = nx.neighbors(G, n=G)
#infected_prob_set = []
for k in tqdm(topk_list):
    topk = k
infected_prob_set = get_topk(degreerank, topk)
print(infected_prob_set)

100%|██████████| 6/6 [00:00<?, ?it/s]['15', '2', '5', '97']



In [8]:
# infected_prob_set

for node in infected_prob_set:
    nbrs = nx.neighbors(G, node)
    print(node)
print(nbrs)
    # nbr = np.random.choice(nbrs)
# print(nbr)

15
2
5
97


In [9]:
time_num_dict_list = list(range(10,20))
time_list = list(range(0,10))
print(time_list, time_num_dict_list)
max_time = max(time_list) + 1
result_matrix = np.zeros((len(time_num_dict_list), max_time))
print(result_matrix)
result_matrix[-1]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
a = [(1,2),(4,3),(6,9)]
print(a[-1])
a0 = np.zeros(len(a),dtype=object)
print(a0)
a0[:] = a
print(a0, a0[-1])
a0

(6, 9)
[0 0 0]
[(1, 2) (4, 3) (6, 9)] (6, 9)


array([(1, 2), (4, 3), (6, 9)], dtype=object)

In [10]:
for index, (row, time_num_dict) in enumerate(zip(result_matrix, time_num_dict_list)):
    print(index, (row, time_num_dict))
    row[:] = list(time_num_dict)[-1]

0 (array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), 10)


TypeError: 'int' object is not iterable

In [37]:
alist = ['a1', 'a2', 'a3']
blist = ['b1', 'b2', 'b3']

for i, (a, b) in enumerate(zip(alist, blist)):
    print(i, a, b)
    print("...",b[-1])

0 a1 b1
... 1
1 a2 b2
... 2
2 a3 b3
... 3
