In [1]:
import pickle
from tqdm import tqdm
import numpy as np
# import matplotlib.pyplot as plt
import networkx as nx
import sys
import random
sys.path.append(r"C:\Users\egbonsisi\ControllerPlacementCodes\Skoltech-PhD-Thesis\_codes\SIR\Influential-nodes-identification-in-complex-networks-via-information-entropy")
from algorithms import *


In [2]:
data_file = 'CEnew' # 'HepPh'
G = nx.read_adjlist(data_file)
G.remove_edges_from(nx.selfloop_edges(G))
nodes = list(nx.nodes(G))
for node in nodes:
    if G.degree(node) == 0:
        G.remove_node(node)

In [3]:
print(nx.number_of_nodes(G), nx.number_of_edges(G))

453 2025


In [4]:
infect_prob = compute_probability(G)*1.5
infect_prob

0.03836535182448562

In [5]:
atio = 1
cover_prob = infect_prob / atio

In [6]:
max_iter = 20000

In [7]:
max_ = 0.009
max_topk = round(max_ * nx.number_of_nodes(G))
print(max_topk)

4


In [8]:
degreerank = degree(G, max_topk)
print(degreerank)
print('done!')

[('15', ' '), ('2', ' '), ('5', ' '), ('97', ' ')]
done!


In [9]:
get_topk(degreerank, max_topk)

['15', '2', '5', '97']

In [10]:


SIR_sample_result = SIR(G, get_topk(degreerank, max_topk), infect_prob,cover_prob, max_iter)
print(SIR_sample_result)

(110, {0: 4, 1: 4, 2: 4, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 5, 10: 6, 11: 6, 12: 6, 13: 6, 14: 7, 15: 7, 16: 7, 17: 8, 18: 9, 19: 9, 20: 10, 21: 10, 22: 11, 23: 11, 24: 11, 25: 12, 26: 13, 27: 13, 28: 14, 29: 14, 30: 14, 31: 15, 32: 16, 33: 16, 34: 16, 35: 16, 36: 16, 37: 16, 38: 16, 39: 16, 40: 16, 41: 17, 42: 18, 43: 20, 44: 20, 45: 21, 46: 21, 47: 21, 48: 21, 49: 21, 50: 21, 51: 21, 52: 21, 53: 21, 54: 21, 55: 21, 56: 21, 57: 21, 58: 21, 59: 21, 60: 21, 61: 21, 62: 21, 63: 21, 64: 21, 65: 22, 66: 22, 67: 22, 68: 22, 69: 22, 70: 22, 71: 22, 72: 22, 73: 22, 74: 22, 75: 22, 76: 22, 77: 22, 78: 22, 79: 22, 80: 22, 81: 22, 82: 22, 83: 22, 84: 22, 85: 22, 86: 22, 87: 22, 88: 22, 89: 22, 90: 22, 91: 22, 92: 22, 93: 22, 94: 22, 95: 22, 96: 22, 97: 22, 98: 22, 99: 22, 100: 22, 101: 22, 102: 22, 103: 22, 104: 22, 105: 22, 106: 22, 107: 22, 108: 22, 109: 22, 110: 22})


In [11]:
# to-get infected set
r = 0.009
top_k = round(nx.number_of_nodes(G) * r)
print(r, top_k)
rank = []

0.009 4


In [12]:
r = [0.0015, 0.003, 0.0045, 0.006, 0.0075, 0.009]
topk_list = []
for k in r:
    topk = round(nx.number_of_nodes(G) * k)
    print(k, topk)
    topk_list.append(topk)

print(topk_list)

0.0015 1
0.003 1
0.0045 2
0.006 3
0.0075 3
0.009 4
[1, 1, 2, 3, 3, 4]


In [13]:
max_ = 0.009
max_topk = round(max_ * nx.number_of_nodes(G))
print(max_topk)

degreerank = degree(G, max_topk)
print(degreerank)

4
[('15', ' '), ('2', ' '), ('5', ' '), ('97', ' ')]


In [15]:
#nbrs = nx.neighbors(G, n=G)
#infected_prob_set = []
for k in tqdm(topk_list):
    topk = k
infected_prob_set = get_topk(degreerank, topk)
print(infected_prob_set)

100%|██████████| 6/6 [00:00<?, ?it/s]

['15', '2', '5', '97']


In [16]:
# infected_prob_set

for node in infected_prob_set:
    nbrs = nx.neighbors(G, node)
    print(node)
print(nbrs)
    # nbr = np.random.choice(nbrs)
# print(nbr)

15
2
5
97


In [17]:
time_num_dict_list = list(range(10,20))
time_list = list(range(0,10))
print(time_list, time_num_dict_list)
max_time = max(time_list) + 1
result_matrix = np.zeros((len(time_num_dict_list), max_time))
print(result_matrix)
result_matrix[-1]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
a = [(1,2),(4,3),(6,9)]
print(a[-1])
a0 = np.zeros(len(a),dtype=object)
print(a0)
a0[:] = a
print(a0, a0[-1])
a0

(6, 9)
[0 0 0]
[(1, 2) (4, 3) (6, 9)] (6, 9)


array([(1, 2), (4, 3), (6, 9)], dtype=object)

In [19]:
for index, (row, time_num_dict) in enumerate(zip(result_matrix, time_num_dict_list)):
    print(index, (row, time_num_dict))
    row[:] = list(time_num_dict)[-1]

0 (array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), 10)


TypeError: 'int' object is not iterable

In [21]:
alist = ['a1', 'a2', 'a3']
blist = ['b1', 'b2', 'b3']

for i, (a, b) in enumerate(zip(alist, blist)):
    print(i, a, b)
    print("...",b[-1])

0 a1 b1
... 1
1 a2 b2
... 2
2 a3 b3
... 3
